export enum DefaultCurrency {
    EURO = 'EURO',
    VARMANN = 'VARMANN',
    IRSAPTESI = 'IRSAPTESI',
    ZEHNDERS = 'ZEHNDERS',
    ARBONIASHOP = 'ARBONIASHOP',
    DEFAULT_PROJECT_EURO = 'DEFAULT_PROJECT_EURO'
}